name: Build & release
on:
    push:
    workflow_dispatch:

jobs:
    build-windows:
        runs-on: windows-2019
        steps:
            - name: Build executable
              uses: sayyid5416/pyinstaller@v1
              with:
                python_ver: '3.12'
                spec: 'app.spec'
                requirements: 'requirements.txt'
                upload_exe_with_name: 'Fix USBDriver.exe'

            # - name: Upload executable
            #   uses: actions/upload-artifact@v4
            #   with: 
            #     name: 'Fix USBDriver'
            #     path: dist/Fix USBDriver.exe
            #     compression-level: 0

    build-ubuntu:
        runs-on: ubuntu-20.04
        steps:
            - name: Build executable
              uses: sayyid5416/pyinstaller@v1
              with:
                python_ver: '3.12'
                spec: 'app.spec'
                requirements: 'requirements.txt'
                upload_exe_with_name: 'Fix USBDriver'

    release-to-github:
        runs-on: ubuntu-latest
        steps:
            - name: get tag
              run: echo "TAG_NAME=v$(date +%Y.%m.%d)" >> $GITHUB_ENV
            - name: release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ env.TAG_NAME }}
                draft: true
                files: |
                    'Fix USBDriver'
                    'Fix USBDriver.exe'
