name: Build app with PyInstaller & release
on:
    workflow_dispatch:

jobs:
    build-windowns:
        runs-on: windows-10
        steps:
            - name: Build executable
              uses: sayyid5416/pyinstaller@v1
              with:
                python_ver: '3.12'
                spec: 'app.spec'
                requirements: 'requirements.txt'
                upload_exe_with_name: 'Fix USBDriver'
    build-ubuntu:
        runs-on: ubuntu-20.04
        steps:
            - name: Build executable
              uses: sayyid5416/pyinstaller@v1
              with:
                python_ver: '3.12'
                spec: 'app.spec'
                requirements: 'requirements.txt'
                upload_exe_with_name: 'Fix USBDriver'
